export const GLOBALTYPES = {
  TOGGLE: 'TOGGLE',
  ALERT: 'ALERT',
  ALL_USERS: 'ALL_USERS',
  GET_CATEGORIES: 'GET_CATEGORIES',
  SUB_CATEGORIES: 'SUB_CATEGORIES',
  CATEGORY_MODAL: 'CATEGORY_MODAL',
  CALLBACK: 'CALLBACK',
};
