export const GLOBALTYPES = {
  AUTH: "AUTH",
  TOKEN: "TOKEN",
  TOGGLE: "TOGGLE",
  ALERT: "ALERT",
  ALL_USERS: "ALL_USERS",
  CATEGORY_MODAL: "CATEGORY_MODAL",
  CALLBACK: "CALLBACK",
  LOGGED_AGENT: "LOGGED_AGENT",
  IS_ADMIN: "IS_ADMIN",
  ALL_ACTIVITY: "ALL_ACTIVITY",
};
